// <auto-generated />
using System;
using AirportTracker.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AirportTracker.Migrations
{
    [DbContext(typeof(AirportContext))]
    [Migration("20241121055525_FreshInit1120")]
    partial class FreshInit1120
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AirportTracker.Models.Aircraft", b =>
                {
                    b.Property<int>("AircraftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AircraftId"), 1L, 1);

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AircraftId");

                    b.ToTable("Aircrafts");

                    b.HasData(
                        new
                        {
                            AircraftId = 1,
                            Capacity = 190,
                            Name = "Boeing 737",
                            Type = "Commercial"
                        },
                        new
                        {
                            AircraftId = 2,
                            Capacity = 180,
                            Name = "Airbus A320",
                            Type = "Commercial"
                        },
                        new
                        {
                            AircraftId = 3,
                            Capacity = 90,
                            Name = "Bombardier CRJ900",
                            Type = "Regional"
                        },
                        new
                        {
                            AircraftId = 4,
                            Capacity = 76,
                            Name = "Embraer E175",
                            Type = "Regional"
                        },
                        new
                        {
                            AircraftId = 5,
                            Capacity = 600,
                            Name = "Boeing 747",
                            Type = "Cargo"
                        },
                        new
                        {
                            AircraftId = 6,
                            Capacity = 396,
                            Name = "Boeing 777",
                            Type = "Commercial"
                        },
                        new
                        {
                            AircraftId = 7,
                            Capacity = 277,
                            Name = "Airbus A330",
                            Type = "Commercial"
                        },
                        new
                        {
                            AircraftId = 8,
                            Capacity = 242,
                            Name = "Boeing 787",
                            Type = "Commercial"
                        },
                        new
                        {
                            AircraftId = 9,
                            Capacity = 555,
                            Name = "Airbus A380",
                            Type = "Commercial"
                        },
                        new
                        {
                            AircraftId = 10,
                            Capacity = 9,
                            Name = "Cessna 208",
                            Type = "Regional"
                        },
                        new
                        {
                            AircraftId = 11,
                            Capacity = 9,
                            Name = "Pilatus PC-12",
                            Type = "Regional"
                        },
                        new
                        {
                            AircraftId = 12,
                            Capacity = 217,
                            Name = "Boeing 767",
                            Type = "Cargo"
                        },
                        new
                        {
                            AircraftId = 13,
                            Capacity = 64,
                            Name = "Lockheed C-130 Hercules",
                            Type = "Cargo"
                        },
                        new
                        {
                            AircraftId = 14,
                            Capacity = 640,
                            Name = "Antonov An-225",
                            Type = "Cargo"
                        },
                        new
                        {
                            AircraftId = 15,
                            Capacity = 47,
                            Name = "Airbus Beluga",
                            Type = "Cargo"
                        });
                });

            modelBuilder.Entity("AirportTracker.Models.Airport", b =>
                {
                    b.Property<int>("AirportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AirportId"), 1L, 1);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shorthand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoURL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AirportId");

                    b.ToTable("Airports");

                    b.HasData(
                        new
                        {
                            AirportId = 1000,
                            City = "Los Angeles",
                            Description = "Los Angeles International Airport (LAX) is one of the busiest and most iconic airports in the world, serving as a major gateway to the United States and a hub for international travel. Located in Westchester, just 18 miles from downtown Los Angeles, it connects travelers to over 180 destinations worldwide. Known for its iconic Theme Building and futuristic design, LAX embodies the dynamic energy of Los Angeles. The airport is home to nine passenger terminals, including the state-of-the-art Tom Bradley International Terminal, which accommodates millions of passengers annually. With world-class dining, shopping, and efficient transit options, LAX offers a premier travel experience while reflecting the cultural diversity of Southern California.",
                            Name = "Los Angeles International Airport",
                            Shorthand = "LAX",
                            State = "California",
                            VideoURL = "https://www.youtube.com/embed/yyVLqUCqWAw"
                        },
                        new
                        {
                            AirportId = 1001,
                            City = "Seattle",
                            Description = "Seattle-Tacoma International Airport (SEA), commonly known as Sea-Tac, is the primary airport serving the Seattle metropolitan area and the Pacific Northwest. Located about 14 miles south of downtown Seattle, it is a major hub for domestic and international travel, particularly to Asia and Alaska. Known for its stunning views of Mount Rainier and Puget Sound, the airport features modern amenities, including a wide range of dining and shopping options. Sea-Tac’s focus on sustainability is evident through initiatives like renewable energy use and eco-friendly terminal designs. With efficient public transit connections, such as the Link Light Rail, it offers convenient access for travelers while showcasing the region’s commitment to innovation and natural beauty.",
                            Name = "Seattle International Airport",
                            Shorthand = "SEA",
                            State = "Washington",
                            VideoURL = "https://www.youtube.com/embed/9f9GJ-xSS3A"
                        },
                        new
                        {
                            AirportId = 1002,
                            City = "Lincoln",
                            Description = "Lincoln Airport (LNK) is a regional airport located in Lincoln, Nebraska, serving as a vital gateway to the city and surrounding areas. Situated about five miles northwest of downtown Lincoln, it provides convenient access for both business and leisure travelers. The airport offers a selection of domestic flights, with connections to major hubs, making it easy to reach destinations across the country. Known for its friendly atmosphere and efficient operations, Lincoln Airport ensures a smooth travel experience without the congestion of larger airports. With its modern facilities and focus on customer service, LNK is a valuable resource for the growing Lincoln community.",
                            Name = "Lincoln Airport",
                            Shorthand = "LNK",
                            State = "Nebraska",
                            VideoURL = "https://www.youtube.com/embed/3w7EiX92W_E"
                        },
                        new
                        {
                            AirportId = 1003,
                            City = "Omaha",
                            Description = "Eppley Airfield (OMA) is the largest airport in Nebraska, located just three miles northeast of downtown Omaha. As a key transportation hub for the region, it offers a range of domestic flights with connections to major cities across the United States. Known for its efficient layout and welcoming atmosphere, the airport provides a stress-free travel experience for passengers. Eppley Airfield features modern amenities, including dining and shopping options, and is equipped with services to accommodate both business and leisure travelers. Its central location and commitment to customer satisfaction make it an essential gateway to Omaha and the surrounding Midwest.",
                            Name = "Eppley Airfield",
                            Shorthand = "OMA",
                            State = "Nebraska",
                            VideoURL = "https://www.youtube.com/embed/lHIJl2K4AW4"
                        },
                        new
                        {
                            AirportId = 1004,
                            City = "New York City",
                            Description = "John F. Kennedy International Airport (JFK) is one of the busiest and most iconic airports in the world, located in Queens, New York City. Serving as a major international gateway to the United States, it offers flights to destinations across six continents. JFK features six passenger terminals, each equipped with world-class amenities, including renowned dining and shopping options that reflect the city’s diverse culture. Known for its historical significance and modern advancements, the airport is a hub for major airlines and a center for global travel. With its extensive transportation links, including the AirTrain and subway, JFK provides seamless connectivity to New York City and beyond.",
                            Name = "John F. Kennedy International Airport",
                            Shorthand = "JFK",
                            State = "New York",
                            VideoURL = "https://www.youtube.com/embed/VeYVasEaBC0"
                        },
                        new
                        {
                            AirportId = 1005,
                            City = "Newark",
                            Description = "Newark Liberty International Airport (EWR) is a major airport serving the New York metropolitan area, located in Newark, New Jersey, just 16 miles southwest of Manhattan. Known for being one of the busiest airports in the United States, it offers a wide range of domestic and international flights, connecting travelers to destinations around the globe. The airport features three terminals with modern amenities, including dining, shopping, and lounges to enhance the passenger experience. As a hub for United Airlines, EWR plays a significant role in global aviation while providing easy access to New York City via NJ Transit and the AirTrain. Its combination of convenience, efficiency, and history makes it a vital gateway to the Northeast.",
                            Name = "Newark Liberty International Airport",
                            Shorthand = "EWR",
                            State = "New Jersey",
                            VideoURL = "https://www.youtube.com/embed/nGkNDVtRMDM"
                        },
                        new
                        {
                            AirportId = 1006,
                            City = "Miami",
                            Description = "Miami International Airport (MIA) is a major international gateway located just 8 miles west of downtown Miami, Florida. Serving as a key hub for travel between the United States, Latin America, and the Caribbean, it is one of the busiest airports in the world for international passenger traffic. MIA features a wide array of amenities, including luxury shopping, dining, and art installations that highlight the city’s vibrant culture. The airport's modern terminals handle millions of passengers annually, offering efficient services for both business and leisure travelers. With its close proximity to popular destinations like South Beach and the Florida Keys, Miami International Airport serves as an essential hub for tourism and global commerce.",
                            Name = "Miami International Airport",
                            Shorthand = "MIA",
                            State = "Florida",
                            VideoURL = "https://www.youtube.com/embed/gnxvQ7atPMk"
                        },
                        new
                        {
                            AirportId = 1007,
                            City = "Dulles",
                            Description = "Washington Dulles International Airport (IAD) is a major international airport located 26 miles west of downtown Washington, D.C., in Virginia. Serving as a key hub for international and domestic travel, it offers connections to over 125 destinations across the globe. Known for its striking design by architect Eero Saarinen, including the iconic terminal building, Dulles features modern facilities and amenities for a seamless travel experience. The airport is a primary hub for United Airlines and handles millions of passengers annually, with services including dining, shopping, and lounges. With its convenient transportation options, including the Silver Line Metro connection, IAD offers easy access to the capital and beyond.",
                            Name = "Washington Dulles International Airport",
                            Shorthand = "IAD",
                            State = "Virginia",
                            VideoURL = "https://www.youtube.com/embed/4w-xPi_Dne0"
                        });
                });

            modelBuilder.Entity("AirportTracker.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"), 1L, 1);

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfSeats")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("BookingId");

                    b.HasIndex("FlightId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("AirportTracker.Models.Employee", b =>
                {
                    b.Property<int>("EmpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpId"), 1L, 1);

                    b.Property<int>("AirportId")
                        .HasColumnType("int");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("EmpId");

                    b.HasIndex("AirportId");

                    b.HasIndex("UserId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("AirportTracker.Models.Flight", b =>
                {
                    b.Property<int>("FlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FlightId"), 1L, 1);

                    b.Property<int>("AircraftId")
                        .HasColumnType("int");

                    b.Property<int?>("AirportId")
                        .HasColumnType("int");

                    b.Property<string>("ArrivalAirport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ArrivalAirportId")
                        .HasColumnType("int");

                    b.Property<string>("DepartureAirport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartureAirportId")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeEmpId")
                        .HasColumnType("int");

                    b.Property<double>("FlightPrice")
                        .HasColumnType("float");

                    b.Property<int?>("PassengerCount")
                        .HasColumnType("int");

                    b.Property<int>("PassengerTotal")
                        .HasColumnType("int");

                    b.Property<DateTime>("TakeOff")
                        .HasColumnType("datetime2");

                    b.Property<int>("TerminalId")
                        .HasColumnType("int");

                    b.HasKey("FlightId");

                    b.HasIndex("AircraftId");

                    b.HasIndex("AirportId");

                    b.HasIndex("EmployeeEmpId");

                    b.HasIndex("TerminalId");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            FlightId = 1,
                            AircraftId = 1,
                            ArrivalAirport = "SEA",
                            ArrivalAirportId = 1001,
                            DepartureAirport = "LAX",
                            DepartureAirportId = 1000,
                            FlightPrice = 150.75,
                            PassengerCount = 0,
                            PassengerTotal = 180,
                            TakeOff = new DateTime(2024, 11, 20, 0, 55, 0, 0, DateTimeKind.Unspecified),
                            TerminalId = 5
                        },
                        new
                        {
                            FlightId = 2,
                            AircraftId = 2,
                            ArrivalAirport = "JFK",
                            ArrivalAirportId = 1004,
                            DepartureAirport = "SEA",
                            DepartureAirportId = 1001,
                            FlightPrice = 220.5,
                            PassengerCount = 0,
                            PassengerTotal = 150,
                            TakeOff = new DateTime(2024, 11, 20, 1, 55, 0, 0, DateTimeKind.Unspecified),
                            TerminalId = 4
                        },
                        new
                        {
                            FlightId = 3,
                            AircraftId = 3,
                            ArrivalAirport = "OMA",
                            ArrivalAirportId = 1003,
                            DepartureAirport = "LNK",
                            DepartureAirportId = 1002,
                            FlightPrice = 180.30000000000001,
                            PassengerCount = 0,
                            PassengerTotal = 90,
                            TakeOff = new DateTime(2024, 11, 20, 2, 55, 0, 0, DateTimeKind.Unspecified),
                            TerminalId = 2
                        },
                        new
                        {
                            FlightId = 4,
                            AircraftId = 4,
                            ArrivalAirport = "EWR",
                            ArrivalAirportId = 1005,
                            DepartureAirport = "LAX",
                            DepartureAirportId = 1000,
                            FlightPrice = 175.0,
                            PassengerCount = 0,
                            PassengerTotal = 200,
                            TakeOff = new DateTime(2024, 11, 20, 3, 55, 0, 0, DateTimeKind.Unspecified),
                            TerminalId = 11
                        },
                        new
                        {
                            FlightId = 5,
                            AircraftId = 9,
                            ArrivalAirport = "SEA",
                            ArrivalAirportId = 1001,
                            DepartureAirport = "JFK",
                            DepartureAirportId = 1004,
                            FlightPrice = 450.0,
                            PassengerCount = 0,
                            PassengerTotal = 555,
                            TakeOff = new DateTime(2024, 11, 20, 4, 55, 0, 0, DateTimeKind.Unspecified),
                            TerminalId = 18
                        },
                        new
                        {
                            FlightId = 6,
                            AircraftId = 5,
                            ArrivalAirport = "OMA",
                            ArrivalAirportId = 1003,
                            DepartureAirport = "MIA",
                            DepartureAirportId = 1006,
                            FlightPrice = 320.0,
                            PassengerCount = 0,
                            PassengerTotal = 600,
                            TakeOff = new DateTime(2024, 11, 20, 5, 55, 0, 0, DateTimeKind.Unspecified),
                            TerminalId = 19
                        },
                        new
                        {
                            FlightId = 7,
                            AircraftId = 8,
                            ArrivalAirport = "JFK",
                            ArrivalAirportId = 1004,
                            DepartureAirport = "LAX",
                            DepartureAirportId = 1000,
                            FlightPrice = 180.5,
                            PassengerCount = 0,
                            PassengerTotal = 242,
                            TakeOff = new DateTime(2024, 11, 20, 6, 55, 0, 0, DateTimeKind.Unspecified),
                            TerminalId = 7
                        },
                        new
                        {
                            FlightId = 8,
                            AircraftId = 7,
                            ArrivalAirport = "LNK",
                            ArrivalAirportId = 1002,
                            DepartureAirport = "EWR",
                            DepartureAirportId = 1005,
                            FlightPrice = 500.0,
                            PassengerCount = 0,
                            PassengerTotal = 300,
                            TakeOff = new DateTime(2024, 11, 20, 7, 55, 0, 0, DateTimeKind.Unspecified),
                            TerminalId = 16
                        },
                        new
                        {
                            FlightId = 9,
                            AircraftId = 2,
                            ArrivalAirport = "SEA",
                            ArrivalAirportId = 1001,
                            DepartureAirport = "LNK",
                            DepartureAirportId = 1002,
                            FlightPrice = 140.0,
                            PassengerCount = 0,
                            PassengerTotal = 200,
                            TakeOff = new DateTime(2024, 11, 20, 8, 55, 0, 0, DateTimeKind.Unspecified),
                            TerminalId = 6
                        },
                        new
                        {
                            FlightId = 10,
                            AircraftId = 3,
                            ArrivalAirport = "MIA",
                            ArrivalAirportId = 1006,
                            DepartureAirport = "LAX",
                            DepartureAirportId = 1000,
                            FlightPrice = 120.0,
                            PassengerCount = 0,
                            PassengerTotal = 180,
                            TakeOff = new DateTime(2024, 11, 20, 9, 55, 0, 0, DateTimeKind.Unspecified),
                            TerminalId = 12
                        },
                        new
                        {
                            FlightId = 11,
                            AircraftId = 4,
                            ArrivalAirport = "IAD",
                            ArrivalAirportId = 1007,
                            DepartureAirport = "JFK",
                            DepartureAirportId = 1004,
                            FlightPrice = 270.5,
                            PassengerCount = 0,
                            PassengerTotal = 76,
                            TakeOff = new DateTime(2024, 11, 20, 10, 55, 0, 0, DateTimeKind.Unspecified),
                            TerminalId = 14
                        },
                        new
                        {
                            FlightId = 12,
                            AircraftId = 10,
                            ArrivalAirport = "JFK",
                            ArrivalAirportId = 1004,
                            DepartureAirport = "LAX",
                            DepartureAirportId = 1000,
                            FlightPrice = 420.75,
                            PassengerCount = 0,
                            PassengerTotal = 500,
                            TakeOff = new DateTime(2024, 11, 20, 11, 55, 0, 0, DateTimeKind.Unspecified),
                            TerminalId = 9
                        },
                        new
                        {
                            FlightId = 13,
                            AircraftId = 9,
                            ArrivalAirport = "SEA",
                            ArrivalAirportId = 1001,
                            DepartureAirport = "OMA",
                            DepartureAirportId = 1003,
                            FlightPrice = 600.0,
                            PassengerCount = 0,
                            PassengerTotal = 300,
                            TakeOff = new DateTime(2024, 11, 20, 12, 55, 0, 0, DateTimeKind.Unspecified),
                            TerminalId = 3
                        },
                        new
                        {
                            FlightId = 14,
                            AircraftId = 6,
                            ArrivalAirport = "LNK",
                            ArrivalAirportId = 1002,
                            DepartureAirport = "JFK",
                            DepartureAirportId = 1004,
                            FlightPrice = 190.30000000000001,
                            PassengerCount = 0,
                            PassengerTotal = 277,
                            TakeOff = new DateTime(2024, 11, 20, 13, 55, 0, 0, DateTimeKind.Unspecified),
                            TerminalId = 15
                        },
                        new
                        {
                            FlightId = 15,
                            AircraftId = 9,
                            ArrivalAirport = "LAX",
                            ArrivalAirportId = 1000,
                            DepartureAirport = "EWR",
                            DepartureAirportId = 1005,
                            FlightPrice = 210.0,
                            PassengerCount = 0,
                            PassengerTotal = 555,
                            TakeOff = new DateTime(2024, 11, 20, 14, 55, 0, 0, DateTimeKind.Unspecified),
                            TerminalId = 16
                        },
                        new
                        {
                            FlightId = 16,
                            AircraftId = 11,
                            ArrivalAirport = "OMA",
                            ArrivalAirportId = 1003,
                            DepartureAirport = "LAX",
                            DepartureAirportId = 1000,
                            FlightPrice = 130.0,
                            PassengerCount = 0,
                            PassengerTotal = 180,
                            TakeOff = new DateTime(2024, 11, 20, 15, 55, 0, 0, DateTimeKind.Unspecified),
                            TerminalId = 9
                        },
                        new
                        {
                            FlightId = 17,
                            AircraftId = 7,
                            ArrivalAirport = "MIA",
                            ArrivalAirportId = 1006,
                            DepartureAirport = "SEA",
                            DepartureAirportId = 1001,
                            FlightPrice = 210.5,
                            PassengerCount = 0,
                            PassengerTotal = 90,
                            TakeOff = new DateTime(2024, 11, 20, 16, 55, 0, 0, DateTimeKind.Unspecified),
                            TerminalId = 10
                        },
                        new
                        {
                            FlightId = 18,
                            AircraftId = 13,
                            ArrivalAirport = "LNK",
                            ArrivalAirportId = 1002,
                            DepartureAirport = "MIA",
                            DepartureAirportId = 1006,
                            FlightPrice = 330.0,
                            PassengerCount = 0,
                            PassengerTotal = 600,
                            TakeOff = new DateTime(2024, 11, 20, 17, 55, 0, 0, DateTimeKind.Unspecified),
                            TerminalId = 20
                        },
                        new
                        {
                            FlightId = 19,
                            AircraftId = 8,
                            ArrivalAirport = "JFK",
                            ArrivalAirportId = 1004,
                            DepartureAirport = "LAX",
                            DepartureAirportId = 1000,
                            FlightPrice = 280.25,
                            PassengerCount = 0,
                            PassengerTotal = 242,
                            TakeOff = new DateTime(2024, 11, 20, 18, 55, 0, 0, DateTimeKind.Unspecified),
                            TerminalId = 7
                        },
                        new
                        {
                            FlightId = 20,
                            AircraftId = 15,
                            ArrivalAirport = "SEA",
                            ArrivalAirportId = 1001,
                            DepartureAirport = "JFK",
                            DepartureAirportId = 1004,
                            FlightPrice = 160.5,
                            PassengerCount = 0,
                            PassengerTotal = 200,
                            TakeOff = new DateTime(2024, 11, 20, 19, 55, 0, 0, DateTimeKind.Unspecified),
                            TerminalId = 13
                        });
                });

            modelBuilder.Entity("AirportTracker.Models.Terminal", b =>
                {
                    b.Property<int>("TerminalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TerminalId"), 1L, 1);

                    b.Property<int>("AirportId")
                        .HasColumnType("int");

                    b.Property<string>("TerminalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TerminalId");

                    b.HasIndex("AirportId");

                    b.ToTable("Terminals");

                    b.HasData(
                        new
                        {
                            TerminalId = 1,
                            AirportId = 1003,
                            TerminalName = "B12"
                        },
                        new
                        {
                            TerminalId = 2,
                            AirportId = 1002,
                            TerminalName = "B12"
                        },
                        new
                        {
                            TerminalId = 3,
                            AirportId = 1003,
                            TerminalName = "B13"
                        },
                        new
                        {
                            TerminalId = 4,
                            AirportId = 1003,
                            TerminalName = "B15"
                        },
                        new
                        {
                            TerminalId = 5,
                            AirportId = 1002,
                            TerminalName = "A12"
                        },
                        new
                        {
                            TerminalId = 6,
                            AirportId = 1002,
                            TerminalName = "A16"
                        },
                        new
                        {
                            TerminalId = 7,
                            AirportId = 1000,
                            TerminalName = "C13"
                        },
                        new
                        {
                            TerminalId = 8,
                            AirportId = 1000,
                            TerminalName = "C16"
                        },
                        new
                        {
                            TerminalId = 9,
                            AirportId = 1000,
                            TerminalName = "C21"
                        },
                        new
                        {
                            TerminalId = 10,
                            AirportId = 1001,
                            TerminalName = "D14"
                        },
                        new
                        {
                            TerminalId = 11,
                            AirportId = 1001,
                            TerminalName = "D16"
                        },
                        new
                        {
                            TerminalId = 12,
                            AirportId = 1000,
                            TerminalName = "D22"
                        },
                        new
                        {
                            TerminalId = 13,
                            AirportId = 1004,
                            TerminalName = "E10"
                        },
                        new
                        {
                            TerminalId = 14,
                            AirportId = 1004,
                            TerminalName = "E11"
                        },
                        new
                        {
                            TerminalId = 15,
                            AirportId = 1004,
                            TerminalName = "E15"
                        },
                        new
                        {
                            TerminalId = 16,
                            AirportId = 1005,
                            TerminalName = "F24"
                        },
                        new
                        {
                            TerminalId = 17,
                            AirportId = 1005,
                            TerminalName = "F14"
                        },
                        new
                        {
                            TerminalId = 18,
                            AirportId = 1005,
                            TerminalName = "F09"
                        },
                        new
                        {
                            TerminalId = 19,
                            AirportId = 1006,
                            TerminalName = "G23"
                        },
                        new
                        {
                            TerminalId = 20,
                            AirportId = 1006,
                            TerminalName = "G17"
                        },
                        new
                        {
                            TerminalId = 21,
                            AirportId = 1006,
                            TerminalName = "G19"
                        });
                });

            modelBuilder.Entity("AirportTracker.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("employed")
                        .HasColumnType("bit");

                    b.Property<string>("fName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("milage")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AirportTracker.Models.Booking", b =>
                {
                    b.HasOne("AirportTracker.Models.Flight", "Flight")
                        .WithMany()
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AirportTracker.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AirportTracker.Models.Employee", b =>
                {
                    b.HasOne("AirportTracker.Models.Airport", "Airport")
                        .WithMany()
                        .HasForeignKey("AirportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AirportTracker.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airport");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AirportTracker.Models.Flight", b =>
                {
                    b.HasOne("AirportTracker.Models.Aircraft", "Aircraft")
                        .WithMany()
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AirportTracker.Models.Airport", "Airport")
                        .WithMany()
                        .HasForeignKey("AirportId");

                    b.HasOne("AirportTracker.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeEmpId");

                    b.HasOne("AirportTracker.Models.Terminal", "Terminal")
                        .WithMany()
                        .HasForeignKey("TerminalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aircraft");

                    b.Navigation("Airport");

                    b.Navigation("Employee");

                    b.Navigation("Terminal");
                });

            modelBuilder.Entity("AirportTracker.Models.Terminal", b =>
                {
                    b.HasOne("AirportTracker.Models.Airport", "Airport")
                        .WithMany()
                        .HasForeignKey("AirportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airport");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AirportTracker.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AirportTracker.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AirportTracker.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AirportTracker.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
